nesting:
  type_level: 2
trailing_comma:
  mandatory_comma: true
disabled_rules:
  - multiple_closures_with_trailing_closure
line_length:
  ignores_comments: true
identifier_name:
  excluded:
    - id
    - kv
